DATA_PATH: '/home/dataset2/Development/SocNav3/dataset'
CONTEXT_FILE: '/home/dataset2/Development/SocNav3/dataset/contexts/anthropic_claude_context.csv'

TRAIN_FILE: '/home/dataset2/Development/SocNav3/dataset/train_set.txt'
DEV_FILE: '/home/dataset2/Development/SocNav3/dataset/val_set.txt'
TEST_FILE: '/home/dataset2/Development/SocNav3/dataset/test_set.txt'

ACTIVATION: 'sigmoid'
ADD_CONTEXT_TO_OUTPUT: True
BATCH_SIZE: 32
DROPOUT: 0.15
GNN_CONCAT: True
GNN_HEADS: [4, 4, 4, 4]
GNN_HIDDEN_SIZE: [256,256,256,256] # It must have the same length as GNN_HEADS
RNN_HIDDEN_SIZE: 256
LINEAR_LAYERS: [256]
LOSS: "mse"
LR: 0.00001
MAX_EPOCHS: 10000
MAX_PATIENCE: 20
NUM_LAYERS: 4
RNN_TYPE: 'GRU' #GRU or LSTM
TIMESTAMP_THRESHOLD: 0.1

SAVE_PLOTS_LOCALLY: True #Set to False if you dont want to save the qualitative test results and expected vs predicted plots
UPLOAD_TO_WANDB: False

Q_TEST_PATH: '/home/dataset2/Development/SocNav3/dataset/qualitative_tests'
Q_TEST_FILE: '/home/dataset2/Development/SocNav3/dataset/qualitative_tests/socnavgym_conf_qualitative_one_static.yaml' 
