
DATA_PATH: '../../../dataset/labeled'
CONTEXT_FILE: '../../../dataset/contexts/anthropic_claude_context.csv'

TRAIN_FILE: 'train_set_socnav3.txt'
DEV_FILE: 'val_set_socnav3.txt'
TEST_FILE: 'test_set_socnav3.txt'

ACTIVATION: 'sigmoid'
ADD_CONTEXT_TO_OUTPUT: True
BATCH_SIZE: 32
DROPOUT: 0.15
GNN_CONCAT: True
GNN_HEADS: 4
HIDDEN_SIZE: 256
LINEAR_LAYERS: [256]
LOSS: "mse"
LR: 0.00001
MAX_EPOCHS: 10000
MAX_PATIENCE: 20
NUM_LAYERS: 4
RNN_TYPE: 'GRU' #GRU or LSTM
TIMESTAMP_THRESHOLD: 0.1

SAVE_PLOTS_LOCALLY: True #Set to False if you dont want to save the qualitative test results and expected vs predicted plots
UPLOAD_TO_WANDB: False

