DATA_PATH: '../../../dataset/labeled/labeled'
CONTEXT_FILE: '../../../dataset/contexts/anthropic_claude_context.csv'

TRAIN_FILE: '../split/train_set_socnav3.txt'
DEV_FILE: '../split/val_set_socnav3.txt'
TEST_FILE: '../split/test_set_socnav3.txt'

ACTIVATION: 'sigmoid'
ADD_CONTEXT_TO_OUTPUT: True
BATCH_SIZE: 4
DATA_AUGMENTATION: True
DROPOUT: 0.15
ONLY_GNN: False
ONLY_METRICS: False
GNN_CONCAT: True
GNN_HEADS: [4, 4, 4, 4]
GNN_HIDDEN_SIZE: [256,256,256,256] # It must have the same length as GNN_HEADS
RNN_HIDDEN_SIZE: 256
LINEAR_LAYERS: [256]
LOSS: "mse"
LR: 0.00001
MAX_EPOCHS: 25
MAX_PATIENCE: 20
NUM_LAYERS: 4
RNN_TYPE: 'GRU' #GRU or LSTM
TIMESTAMP_THRESHOLD: 0.1

SAVE_PLOTS_LOCALLY: True #Set to False if you dont want to save the qualitative test results and expected vs predicted plots
UPLOAD_TO_WANDB: False
PROJECT_NAME: 'SN3-GNN'
SEED: 123456


Q_TEST_PATH: '../../../etc/qualitative_tests'
Q_TEST_FILE: '../../../etc/qualitative_tests/socnavgym_conf_qualitative_one_static.yaml' 
